name: solar-system-cicd

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI  : 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME : ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD : ${{ secrets.MONGO_PASSWORD }}

jobs: 
    unit-test:
        name: Unit Tests on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [19,20]                ## test against Node.js versions 19 and 20 
                os:  [ubuntu-latest,ubuntu-22.04]   ## run tests on both Ubuntu and MacOS
                exclude:
                - os: ubuntu-latest
                  node-version: 19
                - os: ubuntu-22.04
                  node-version: 19
        services:
            mongo:
                image: siddharth67/mongo-db:non-prod              ## Use MongoDB version 
                ports:
                    - 27017:27017
        
        env:                                                  ## Override global env vars for mongo service
            MONGO_URI  : 'mongodb://localhost:27017/superData'
            MONGO_USERNAME : non-prod-user                ## can use repo variables as well
            MONGO_PASSWORD : non-prod-password            ## can use repo secrets as well
              
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache Dependencies        ##  Cache npm dependencies to speed up build
              uses: actions/cache@v4
              with:      
                path: node_modules
                key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}    ## Cache key based on OS and package-lock.json

            - name: Install dependencies
              run: npm install

            - name: Run unit tests
              run: npm test  
              ##continue-on-error: true       ## Continue even if tests fail to allow artifact upload

            - name: Upload test results
              if: always()                      ## Ensure this step runs even if previous steps fail
              uses: actions/upload-artifact@v4
              with:
                  name: Unit-Test_results-${{ matrix.os }}-node-${{ matrix.node-version }}  ## Name of the artifact
                  path: test-results.xml


    code-coverage:
        name: Code Coverage and Reporting
        container: 
            image: node:18                     ## Use Node.js 18 Docker image for consistency
        
        services:
            mongo:
                image: siddharth67/mongo-db:non-prod              ## Use MongoDB version 
                options:
                  --name mongo             ## Naming the container for easier reference
        
        env:                                                  ## Override global env vars for mongo service
            MONGO_URI  : 'mongodb://mongo:27017/superData'  ## Note the hostname 'mongo' matches the service name
            MONGO_USERNAME : non-prod-user                ## can use repo variables as well
            MONGO_PASSWORD : non-prod-password            ## can use repo secrets as well

        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # - name: Setup Node.js 18                  ## Not needed as we are using a Node.js container
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: 18

            - name: Cache Dependencies        ##  Cache npm dependencies to speed up build
              uses: actions/cache@v4
              with:      
                path: node_modules
                key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}    ## Cache key based on OS and package-lock.json

            - name: Install dependencies
              run: npm install

            - name: Run tests with coverage
              continue-on-error: true       ## Continue even if tests fail to allow coverage report upload
              run: npm run coverage

            - name: Upload coverage report
              ##if: always()                      ## Ensure this step runs even if previous steps fail
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report
                  path: coverage/
                  retention-days: 5           ## Keep the report for 5 days default is 90 days

    Containerization:
        name: Build Test and Push Images to docker and github registry
        runs-on: ubuntu-latest
        permissions:
            contents: read       ## Permission to read repository contents
            packages: write        ## Permission to push to GitHub Container Registry
        needs: [unit-test, code-coverage]   ## Ensure tests and coverage complete before building image
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKER_HUB_USERNAME }}   ## Docker Hub username stored in GitHub repository Variables
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}    ## Docker Hub access token stored in GitHub repository Secrets

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io       ## GitHub Container Registry
                  username: ${{ github.repository_owner }}  ## GitHub username - predefined context variable
                  password: ${{ secrets.GITHUB_TOKEN }} ## GitHub token for authentication - created automatically by GitHub

            - name: Build Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .              ## Build context is the current directory (path to Dockerfile)
                  push: false             ## Do not push yet  
                  tags: ${{ vars.DOCKER_HUB_USERNAME }}/solar-system-app:${{ github.sha }}   ## Tag image with commit SHA

            - name: Test the Docker Image
              run: |
                  docker images
                  docker run -d -p 3000:3000 --name solar-test \
                  -e MONGO_URI='${{ env.MONGO_URI }}' \
                  -e MONGO_USERNAME='${{ vars.MONGO_USERNAME }}' \
                  -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
                  ${{ vars.DOCKER_HUB_USERNAME }}/solar-system-app:${{ github.sha }}

                  sleep 10   ## Wait for container to start

                  export IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-test)
                  echo "Container IP: $IP"
                  echo testing image url using wget
                  wget -qO- http://localhost:3000/live | grep live

            - name: Push Container images to docker and github registry
              uses: docker/build-push-action@v4 
              with:
                  context: .              ## Build context is the current directory (path to Dockerfile)
                  push: true             ## Push the image to Docker Hub 
                  tags: | 
                    ${{ vars.DOCKER_HUB_USERNAME }}/solar-system-app:${{ github.sha }}   
                    ghcr.io/${{ github.repository_owner }}/solar-system-app:${{ github.sha }}  


    Deploy:
        name: Deploy to Kubernetes Cluster using kubectl
        runs-on: ubuntu-latest
        needs: Containerization    ## Ensure containerization is done before deployment
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Kubectl
              uses: azure/setup-kubectl@v4 
              with:
                version: 'v1.26.0'   ## Specify kubectl version

            - name: Configure Kubeconfig
              uses: azure/k8s-set-context@v4 
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.KUBECONFIG }}

            - name: Fetch Kubernetes Details
              run: |
                kubectl version --short
                echo ----------------------
                kubectl cluster-info
                echo ======================
                kubectl get nodes

            - name: get Ingress IP
              id: ingress_ip
              run: |
                INGRESS_IP=$(kubectl get svc nginx-ingress-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
                echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV
                echo "Ingress IP is $INGRESS_IP"

            - name: Replace tokens in development manifests
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["kubernetes/development/*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS }}
                IMAGE: ${{ vars.DOCKER_HUB_USERNAME }}/solar-system-app:${{ github.sha }}
                INGRESS_IP: ${{ env.INGRESS_IP }}

            - name: Verify variables replacement in manifests 
              run: |
                cat kubernetes/development/*.yaml
                