name: solar-system-cicd

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI  : 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME : ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD : ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-test:
        name: Unit Tests on Node.js ${{ matrix.node-version }} and ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [19,20]                ## test against Node.js versions 19 and 20 
                os:  [ubuntu-latest,ubuntu-20.04]   ## run tests on both Ubuntu and MacOS
                exclude:
                - os: ubuntu-latest
                  node-version: 19
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Cache Dependencies        ##  Cache npm dependencies to speed up build
              uses: actions/cache@v4
              with:      
                path: node_modules
                key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}    ## Cache key based on OS and package-lock.json

            - name: Install dependencies
              run: npm install

            - name: Run unit tests
              run: npm test  
              ##continue-on-error: true       ## Continue even if tests fail to allow artifact upload

            - name: Upload test results
              if: always()                      ## Ensure this step runs even if previous steps fail
              uses: actions/upload-artifact@v4
              with:
                  name: Unit-Test_results-${{ matrix.os }}-node-${{ matrix.node-version }}  ## Name of the artifact
                  path: test-results.xml


    code-coverage:
        name: Code Coverage and Reporting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Cache Dependencies        ##  Cache npm dependencies to speed up build
              uses: actions/cache@v4
              with:      
                path: node_modules
                key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}    ## Cache key based on OS and package-lock.json

            - name: Install dependencies
              run: npm install

            - name: Run tests with coverage
              continue-on-error: true       ## Continue even if tests fail to allow coverage report upload
              run: npm run coverage

            - name: Upload coverage report
              ##if: always()                      ## Ensure this step runs even if previous steps fail
              uses: actions/upload-artifact@v4
              with:
                  name: coverage-report
                  path: coverage/
                  retention-days: 5           ## Keep the report for 5 days default is 90 days