name: solar-system-cicd

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'feature/*'

env:
    MONGO_URI  : 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME : ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD : ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              run: npm install

            - name: Run unit tests
              run: npm test  
              continue-on-error: true

            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                  name: Unit-Test_results
                  path: test-results.xml
